-- MySQL Script generated by MySQL Workbench
-- Mon May 21 17:49:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zoo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zoo` DEFAULT CHARACTER SET utf8 ;
USE `zoo` ;

-- -----------------------------------------------------
-- Table `zoo`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`Zonas` (
  `id_zona` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `extension` INT ZEROFILL NULL,
  PRIMARY KEY (`id_zona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`Tipos_vegetacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`Tipos_vegetacion` (
  `id_tipo_vegetacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_vegetacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`Habitats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`Habitats` (
  `id_habitat` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `clima` VARCHAR(45) NULL,
  `id_tipo_vegetacion` INT NOT NULL,
  PRIMARY KEY (`id_habitat`),
  INDEX `fk_Habitats_Tipos_vegetacion1_idx` (`id_tipo_vegetacion` ASC),
  CONSTRAINT `fk_Habitats_Tipos_vegetacion1`
    FOREIGN KEY (`id_tipo_vegetacion`)
    REFERENCES `zoo`.`Tipos_vegetacion` (`id_tipo_vegetacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`Especies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`Especies` (
  `id_especie` INT NOT NULL AUTO_INCREMENT,
  `nombre_esp` VARCHAR(45) NOT NULL,
  `nombre_cien` VARCHAR(45) NOT NULL,
  `id_zona` INT NOT NULL,
  `id_habitat` INT NOT NULL,
  PRIMARY KEY (`id_especie`),
  INDEX `fk_Especies_Zonas_idx` (`id_zona` ASC),
  INDEX `fk_Especies_Habitats1_idx` (`id_habitat` ASC),
  CONSTRAINT `fk_Especies_Zonas`
    FOREIGN KEY (`id_zona`)
    REFERENCES `zoo`.`Zonas` (`id_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Especies_Habitats1`
    FOREIGN KEY (`id_habitat`)
    REFERENCES `zoo`.`Habitats` (`id_habitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`Continentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`Continentes` (
  `id_continente` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_continente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`Habitats_x_continentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`Habitats_x_continentes` (
  `id_habitat` INT NOT NULL,
  `id_continente` INT NOT NULL,
  PRIMARY KEY (`id_habitat`, `id_continente`),
  INDEX `fk_Habitats_has_Continentes_Continentes1_idx` (`id_continente` ASC),
  INDEX `fk_Habitats_has_Continentes_Habitats1_idx` (`id_habitat` ASC),
  CONSTRAINT `fk_Habitats_has_Continentes_Habitats1`
    FOREIGN KEY (`id_habitat`)
    REFERENCES `zoo`.`Habitats` (`id_habitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habitats_has_Continentes_Continentes1`
    FOREIGN KEY (`id_continente`)
    REFERENCES `zoo`.`Continentes` (`id_continente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`Itinerarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`Itinerarios` (
  `codigo` INT NOT NULL,
  `duracion` INT ZEROFILL NOT NULL,
  `longitud` INT ZEROFILL NOT NULL,
  `nro_especies` INT NOT NULL,
  `max_visitantes` INT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`Detalles_Itinerario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`Detalles_Itinerario` (
  `id_zona` INT NOT NULL,
  `codigo` INT NOT NULL,
  PRIMARY KEY (`id_zona`, `codigo`),
  INDEX `fk_Zonas_has_Itinerarios_Itinerarios1_idx` (`codigo` ASC),
  INDEX `fk_Zonas_has_Itinerarios_Zonas1_idx` (`id_zona` ASC),
  CONSTRAINT `fk_Zonas_has_Itinerarios_Zonas1`
    FOREIGN KEY (`id_zona`)
    REFERENCES `zoo`.`Zonas` (`id_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zonas_has_Itinerarios_Itinerarios1`
    FOREIGN KEY (`codigo`)
    REFERENCES `zoo`.`Itinerarios` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`Guias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`Guias` (
  `legajo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NULL,
  `fecha_ingreso` DATE NOT NULL,
  PRIMARY KEY (`legajo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`Horarios_guias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`Horarios_guias` (
  `codigo` INT NOT NULL,
  `legajo` INT NOT NULL,
  `horario` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`codigo`, `legajo`),
  INDEX `fk_Itinerarios_has_Guias_Guias1_idx` (`legajo` ASC),
  INDEX `fk_Itinerarios_has_Guias_Itinerarios1_idx` (`codigo` ASC),
  CONSTRAINT `fk_Itinerarios_has_Guias_Itinerarios1`
    FOREIGN KEY (`codigo`)
    REFERENCES `zoo`.`Itinerarios` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itinerarios_has_Guias_Guias1`
    FOREIGN KEY (`legajo`)
    REFERENCES `zoo`.`Guias` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
